### ISSUE TITLE
Graceful error handling for mis-named datamap csv headers

### ISSUE THREAD

**Issue by yulqen** [yulqen/datamaps#10]
More error handling you could try with the same set of documents is when the datamap.cvs has incorrect headings. E.g. type something other than 'cell_ref' in column A heading. This will also cause a crash. 
Cheers, Will.

_Originally posted by @banillie in https://github.com/yulqen/datamaps/issues/9#issuecomment-689384783_

**Comment by banillie** [comment]
as above datamap.csv heading needs to be `cellreference` exactly or causes a crash. 

It would prob be best to actually change the requirement to `cell_reference` to be consistent with the other headers.

**Comment by yulqen** [comment]
Looking at the code, `cell_reference` , `cell_ref`, `cellref`, `cellreference` should all work.

https://github.com/yulqen/bcompiler-engine/blob/414a1729928942d2bdde48e5cb743c4a80b687b1/engine/utils/extraction.py#L383
`    _good_cellref = ["cell_reference", "cell_ref", "cellref", "cellreference"]`

Will have to run some tests if you're seeing a problem - or put up the stacktrace so I can see what's going on.

**Comment by banillie** [comment]
Ok. I've tried those above combos and they work fine. I can't remember what the combo was that caused a crash, but it will have been different to those of course. so leave for now. thanks.

**Comment by yulqen** [comment]
I think there are enough options the user can choose to name the field here, so closing.
