### ISSUE TITLE
change master.quarter format 

### ISSUE THREAD

**Issue by banillie** [yulqen/datamaps#12]
@yulqen Is it possible to change the `master.quarter` structure so that `str(master.quarter)` returns `[quarter]_[year_one]_[year_two]` i.e. `Q2_20_21`, rather than `Q2 20/21`? It would be helpful for automatically including the quarter stamp in the saving of output files e.g. `data_analysis_Q2_20_21` . 
Just an idea. Sure it wont be difficult to develop a function to do this in analysis_engine also.

**Comment by yulqen** [comment]
Here you go. Using pythons regular expressions library - [regular expressions](https://en.wikipedia.org/wiki/Regular_expression).

Makes more sense for you to convert the text to whatever you want rather than changing the API.

```python
import re

def make_file_friendly(quarter_str: str) -> str:

    # regular expressions start with an "r" in python. This is the crucial bit - a pattern that states what string you want to match.
    regex = r"Q(\d) (\d+)\/(\d+)"  
    
    # we use the `search()` function to match the string we want with the pattern
    m = re.search(regex, quarter_str)

   # this returns the string we want, keeping the bits in brackets from `regex` and writing them out separated by underscores instead of the forward slash.
    return re.sub(regex, r"Q\1_\2_\3", test_str)

# just testing it works
test_str = "Q2 10/23"
print(make_file_friendly(test_str))
```

**Comment by banillie** [comment]
Excellent. Thanks for providing this.
