### ISSUE TITLE
not all files processed via -z command

### ISSUE THREAD

**Issue by banillie** [yulqen/datamaps#18]
Instance of some files being passed and not processed via the -z command. I'll send you the files to test. I know that the reason one of them doesn't process is because the file is saved as XLSX (if you amend the file to lowercase it works fine, but this is a bit fiddly) is this something datamaps can handle? I can't easily determining why the other one isn't being processed. 

command was `datamaps import templates -m -d [dm_path] -z [zip_file_path]`

**Comment by yulqen** [comment]
I can check if I get the files.

**Comment by yulqen** [comment]
the two files that aren't coming thought are DFT-047-MIDLANDS RAIL HUB-April 2021 and DFT-052-LOWER THAMES CROSSING-April 2021. The lower thames crossing one is obvious as had capital XLSX (somehow), but midlands not clear,

**Comment by banillie** [comment]
@yulqen I done more testing of the `-z` command I think the first file in the zip file is not being processed. You can check this with the zip I have sent to you. Therefore the causes of two files not being processed are 1) first file in zip skipped 2) uppercase XLSX file type.

**Comment by yulqen** [comment]
@banillie Thank you I will investigate. Fix on the way.

**Comment by yulqen** [comment]
I think you are correct - the first file not being processed for some reason....

**Comment by yulqen** [comment]
Bug fixed. Got to run tests now before releasing a new version.

**Comment by yulqen** [comment]
Fixed in `datamaps` v1.1.4. Please update and test!
