### ISSUE TITLE
export master command -d flag file path error

### ISSUE THREAD

**Issue by banillie** [yulqen/datamaps#19]
When doing the command `datamaps export master [PATH to master] -d [PATH to datamap.csv]` get the error:
```
CRITICAL - Cannot find C:\Users\Standalone\Documents\datamaps\input\Documents\datamaps\Q3_dm_export.csv
```
I've kept the actual file path in there so you can see that the file path is being repeated. i.e. has Documents twice. 
You only need a dummy master and datamap to check this.

**Comment by yulqen** [comment]
If you put the datamap in another location (Desktop?) and call again, do you get a similar error?

**Comment by banillie** [comment]
Yes. ` CRITICAL - Cannot find C:\Users\Standalone\Documents\datamaps\input\Desktop\datamap_export.csv`

**Comment by yulqen** [comment]
Can you please email (personal email) me a copy of the current blank_template.xlsm file so I can test with most up to date files? I've probably got one around somewhere on another machine but if you an ping it in an email, that would be great. Ta.

**Comment by banillie** [comment]
Done and done.

**Comment by yulqen** [comment]
Unable to reproduce.

What is the exact command, Will - particularly what does the path to the datamap file look like in the `-d` flag? I've tried both relative and absolute path with no problems. Not tested on Windows.

**Comment by banillie** [comment]
Yes this error was on Windows. However, given you couldn't reproduce did some further testing and got it to work with absolute rather than relative file paths. so `datamaps export master C:\Users\Standalone\Documents\datamaps\output\master.xlsx -d C:\Users\Standalone\Documents\datamaps\datamap_export.csv` works, but `datamaps export master Documents\datamaps\output\master.xlsx -d Documents\datamaps\datamap_export.csv` gets the error as above.

**Comment by yulqen** [comment]
The second example you give (the relative path) wouldn't work unless your
working directory is C:\Users\Standalone.  You could use `echo %cd%` in the command prompt to check that. Assuming that is the case, I'm not sure what's going on here and would have to do some testing in Windows. But advice for now is use the absolute path.

Don't forget your can write your commands into bash scripts if you're doing them
a lot!  You don't have to keep typing 'em out...

On 29-04-2021, Will Grant wrote:
>Yes this error was on Windows. However, given you couldn't reproduce did some further testing and got it to work with absolute rather than relative file paths. so `datamaps export master C:\Users\Standalone\Documents\datamaps\output\master.xlsx -d C:\Users\Standalone\Documents\datamaps\datamap_export.csv` works, but `datamaps export master Documents\datamaps\output\master.xlsx -d Documents\datamaps\datamap_export.csv` gets the error as above.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/yulqen/datamaps/issues/19#issuecomment-829062680

-- 

Matthew Lemon
Email: ***@***.***

**Comment by banillie** [comment]
Yeap working directory is C:\User\Standalone so weird.

**Comment by yulqen** [comment]
Use absolute paths for now to be safe; leave the issue open, I'll look into
this.
