### ISSUE TITLE
error handling for merged cell in template 

### ISSUE THREAD

**Issue by banillie** [yulqen/datamaps#9]
Hi Matt, another error handling message you might like to include is when data is being transferred into a merged cell within the template sheet, which causes a crash. This happened via some testing we have done recently. I can send you the necessary docs to recreate if you like. 
Thanks, Will.

**Comment by yulqen** [comment]
Hi Will - yes, if you could send me all relevant files (datamap, master, template, blank - whatever) and a summary of what command was attempted, and what the result was, that would be great. Will take a look.  Thanks for raising.

**Comment by banillie** [comment]
Have sent to you Matt. 
More error handling you could try with the same set of documents is when the datamap.cvs has incorrect headings. E.g. type something other than 'cell_ref' in column A heading. This will also cause a crash. 
Cheers, Will.

**Comment by yulqen** [comment]
Moved the csv_headers one to a new issue. Have the files for this issue and working on it.
